<?php

require './../index.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-20 at 11:44:29.
 */
class CalculatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Calculator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Calculator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (1,1) == 2.
     *
     * @covers Calculator::add
     */
    public function testAdd() {
        $this->assertEquals(
                2, $this->object->add(1, 1)
        );
    }

    /**
     * Generated from @assert (2,4) == 6.
     *
     * @covers Calculator::add
     */
    public function testAdd2() {
        $this->assertEquals(
                6, $this->object->add(2, 4)
        );
    }

}
